= Make Alpine Linux VM Image
:script-name: alpine-make-vm-image
:script-sha1: 2b2b0332f8b53eda6b03ee7f4bcf75e12802941f
:gh-name: tryauuum/{script-name}
:version: 0.9.0-custom

ifdef::env-github[]
image:https://github.com/{gh-name}/workflows/CI/badge.svg["Build Status", link="https://github.com/{gh-name}/actions"]
endif::env-github[]

This project provides a script for making SUPER INSECURE AND OPEN TO WORLD (E.G. PASSWORDLESS SSH ROOT ACCESS) customized https://alpinelinux.org/[Alpine Linux] disk images for virtual machines.

== Requirements

* Linux system with common userland (Busybox or GNU coreutils)
* POSIX-sh compatible shell (e.g. Busybox ash, dash, Bash, ZSH)
* qemu-img and qemu-nbd (automatically installed by the script if running on Alpine)
* e2fsprogs (for ext4), btrfs-progs (for Btrfs), or xfsprogs (for XFS) (automatically installed by the script if running on Alpine)


== Usage

Read documentation in link:{script-name}[{script-name}].
See link:.github/workflows/ci.yml[] for GitHub Actions example.

You can copy link:{script-name}[{script-name}] into your repository or download it on demand, e.g.:

[source, sh, subs="+attributes"]
wget https://raw.githubusercontent.com/{gh-name}/v{version}/{script-name} \
    && echo '{script-sha1}  {script-name}' | sha1sum -c \
    || exit 1

